title: Java on Azure Spring Apps
description: This lab walks you through the creation Azure Spring Apps integrated with multiple Azure service, and deploy an application with Front End supported by various backend microservices
theme: just-the-docs

# url: https://Azure-Samples.github.io/java-microservices-asa-e-lab

aux_links:
  "Java microservices on Azure Spring Apps Standard": 
    - "https://github.com/sebafo/java-microservices-asa-aca-lab"


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
